import React,{ReactNode,useState,useEffect} from "react";
import Head from "next/head";
import Aside from "../../components/layout/Asides";
import Header from "../../components/layout/Header";
import AsideForMobile from "../../components/atom/AsideForMobile";
import Vision from "../../components/molecule/Vision";



function Series() {

  const [asides,setasides]=useState<ReactNode>(); 
  const [headers,setheaders]=useState<ReactNode>(Header); 
  const [screens,setscreens]=useState<Number>(); 

  const aside=(typeof window !== 'undefined') && (screen.width <=425 )?<AsideForMobile/>:<Aside/>;
  const header=((typeof window !== 'undefined') && (screen.width <=425 ))?null:<Header />

useEffect(()=>{
  setasides(aside);
  setheaders(header)
},[screens])


setInterval(()=>{
  if (screen.width <=425 || screen.width) {
    setscreens(screen.width)
  }
},100)

const metaData=[{
  title:"Trending Series",
  data:[{
    src:"./foot.webp",
    alt:"david",
   
},
  {
    src:"./foot.webp",
    alt:"david",
    
       
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david",
    
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },
  
  ]
},
{
  title:"Popular Series",
  data:[{
    src:"./foot.webp",
    alt:"david",
   
},
  {
    src:"./foot.webp",
    alt:"david",
    
       
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david",
    
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },
  
  ]
},

{
  title:"Top Rated Series",
  data:[{
    src:"./foot.webp",
    alt:"david",
   
},
  {
    src:"./foot.webp",
    alt:"david",
    
       
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david",
  
     },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },
  
  ]
},

{
  title:"Live Now",
  data:[{
    src:"./foot.webp",
    alt:"david",
   
},
  {
    src:"./foot.webp",
    alt:"david",
    
       
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david",
    
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },
  
  ]
},

{
  title:"New Episodes",
  data:[{
    src:"./foot.webp",
    alt:"david",
   
},
  {
    src:"./foot.webp",
    alt:"david",
    
       
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david",
    
  },{
    src:"./foot.webp",
    alt:"david",
   
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },{
    src:"./foot.webp",
    alt:"david"
  },
  
  ]
},

]





  return (
    <>
    <Head>
      <title>Series</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
   
<main className="serie_main">
 {asides}
 
  <Vision metaData={metaData}/>
  </main>
  </>
  )
}

export default Series