import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>accuile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
            <header className="home_header">
        <img src="/logo.svg" alt="logo Disney" className="logo" />

        <Link href={"/user"} type="button" className="btnlogin">
          Login
        </Link>
      </header>

      <main className="home_main">

        <section className="get">

          <img src="/cta-logo-one.svg" alt="logo hulu Disney Espn" className="line_logo_one"  />

          <div className="access">

            <button type="button" className="all">GET ALL THERE</button>

            <p className="Premier">Get Premier Access to Raya and the Last Dragon 
              for an additional fee with a Disney+ subscription.
               As of 03/26/21, the price of Disney+ and The Disney 
               Bundle will increase by $1.</p>

          </div>
          <img src="/cta-logo-two.png" className="logo_plus"  />

        </section>

      </main>
     
    </>
  );
}
