import React from "react";
import Head from "next/head";
import Aside from "../components/layout/Asides";
import Header from "../components/layout/Header";
import Scrolling from "../components/molecule/Scrolling";

function User() {
  return (
    <>
    <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="user_main">
     <Aside/>
   <Scrolling/>
     





      </main>


    </>
  )
}

export default User