"use client"
import React, { ReactNode, useEffect, useState } from "react";
import Head from "next/head";
import Aside from "../components/layout/Asides";
import Header from "../components/layout/Header";
import Scrolling from "../components/molecule/Scrolling";
import AsideForMobile from "../components/atom/AsideForMobile";


function User() {

  const [asides,setasides]=useState<ReactNode>(); 
  const [headers,setheaders]=useState<ReactNode>(Header); 
  const [screens,setscreens]=useState<Number>(); 

  const aside=(typeof window !== 'undefined') && (screen.width <=425 )?<AsideForMobile/>:<Aside/>;
  const header=((typeof window !== 'undefined') && (screen.width <=425 ))?null:<Header />

useEffect(()=>{
  setasides(aside);
  setheaders(header);


const timer=setInterval(()=>{
    if (screen.width <=425 || screen.width) {
      setscreens(screen.width)
    }
  },1000)
return()=>{
clearInterval(timer)

}

},[screens])





return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {  headers}
      <main className="user_main">
      {asides}  
        <Scrolling />
      </main>
    </>
  );
}

export default User;
